### ISSUE TITLE
just before 5

### ISSUE THREAD

**Issue by chanezon** [dockersamples/ee-workshop#41]
we should not expose port 8000 used for debugging, confusing

**Comment by chanezon** [comment]
port 8080 or nodeport
published and target 8080
explain that in the text plus look at ui for when port is ezxposed, maybe expose url of the expose port instead of node port.

**Comment by chanezon** [comment]
no it's the swarm service that is exposed on 8080: add a step to detruire stack swarm

**Comment by spara** [comment]
port 8000 removed in the hybrid app and in the workshop README
