### ISSUE TITLE
In Task 2, the java-app stack can't add networks

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/ee-workshop#52]
Using the compose file in the ee-workshop instructions results in an error when creating the networks. Removing the networks allows the stack to deploy but the app isn't exposed and so can't be accessed by the endpoint+`/java-web`.

**Comment by spara** [comment]
This has been fixed in the README, but I think we need to go over the workflow with regards to manually setting the networks in the previous section before I close this issue.
