### ISSUE TITLE
the hybrid PWD sandbox doesn't appear to have a windows host dcsf2018

### ISSUE THREAD

**Issue by atteroAnimus** [dockersamples/ee-workshop#66]
When connecting to the PWD interface at https://docker.ly/hol18-hybrid, there doesn't appear to be a windows host available.  The instructions where it says, "Switch back to the PWD interface, and click the name of your Windows node."  It is not clear where that node is supposed to be.  Since this requirement is essential for the rest of the lab, this needs to be clearer.  I was unable to do the hands-on part of any part of the lab where a windows host is required.

**Comment by ManoMarks** [comment]
Hi, yeah we've experienced some redirect issues from the forms we are using. If you're still in the area, please connect with the Docker employees in the hands-on-labs area
